blueprint:
  name: ESPHOME MANU.CLICK EVENT
  description: Control Events From NODE-RED
  domain: automation
  input:
    button:
      name: Switch
      description: Which Binary Sensor to use?
      selector:
        entity:
          domain: binary_sensor

    button_clicked:
      name: Short click
      default: []
      selector:
        action: {}
    button_double_clicked:
      name: Double click
      default: []
      selector:
        action: {}
    button_pressed:
      name: Short + Long click
      default: []
      selector:
        action: {}
    button_clicked_pressed:
      name: Long click
      default: []
      selector:
        action: {}
    button_released:
      name: Button release after (short +) long press
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: "manu.click"
  event_data:
    button: !input 'button'
action:
- variables:
    event: '{{ trigger.event.data.type }}'
- choose:
  - conditions:
    - '{{ event == "clicked" }}'
    sequence: !input 'button_single'
  - conditions:
    - '{{ event == "double_clicked" }}'
    sequence: !input 'button_double'
  - conditions:
    - '{{ event == "pressed" }}'
    sequence: !input 'button_short_long'
  - conditions:
    - '{{ event == "clicked_pressed" }}'
    sequence: !input 'button_long'
  - conditions:
    - '{{ event == "released" }}'
    sequence: !input 'button_released'
